version: '3.1'

services: 

   db:
      image: mysql:5.7
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: Knd7r53p
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: Knd7r53p
      volumes: 
         - db:/var/lib/mysql

   wordpress:
      depends_on: 
         - db
      image: wordpress:latgest
      ports: 
         - 8000:80
      restart: always
      environment:
         WORDPRESS_DB_HOST: db:3306
         WORDPRESS_DB_USER: wordpress
         WORDPRESS_DB_PASSWORD: wordpress
         WORDPRESS_DB_NAME: wordpress
      volumes: 
         - wordpress:/var/www/html

   volumes:
      db:
      wordpress:
